# Generated by Django 5.0.1 on 2025-10-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolpermiso',
            options={'managed': False},
        ),
    ]
