# Generated by Django 5.0.1 on 2025-10-13 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_rolpermiso_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'managed': False},
        ),
    ]
