# Generated by Django 5.0.1 on 2025-10-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_authidentidad_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rut_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rut',
            field=models.TextField(blank=True, null=True),
        ),
    ]
