# Generated by Django 5.0.1 on 2025-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
