# Generated by Django 5.0.1 on 2025-11-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dispositivo_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediccionconsumo',
            name='consumo_real_kwh',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
