CREATE TABLE "usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE,
  "contrasena_hash" varchar,
  "rut" varchar UNIQUE,
  "nombre" varchar,
  "apellido" varchar,
  "direccion" varchar,
  "comuna" varchar,
  "tipo_vivienda" varchar,
  "fecha_registro" datetime,
  "ultimo_acceso" datetime,
  "activo" boolean DEFAULT true,
  "es_administrador" boolean DEFAULT false
);

CREATE TABLE "dispositivos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "nombre" varchar,
  "tipo_dispositivo" varchar,
  "potencia_promedio" decimal,
  "horas_uso_diario" decimal,
  "activo" boolean DEFAULT true,
  "fecha_registro" datetime
);

CREATE TABLE "registros_consumo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "fecha" date,
  "consumo_kwh" decimal,
  "costo_clp" decimal,
  "dispositivo_id" int,
  "lectura_manual" boolean DEFAULT true,
  "fecha_registro" datetime
);

CREATE TABLE "predicciones_consumo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "fecha_prediccion" date,
  "periodo_inicio" date,
  "periodo_fin" date,
  "consumo_predicho_kwh" decimal,
  "nivel_alerta" varchar,
  "fecha_registro" datetime
);

CREATE TABLE "notificaciones" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "tipo" varchar,
  "mensaje" text,
  "leida" boolean DEFAULT false,
  "fecha_creacion" datetime
);

CREATE TABLE "metricas_ahorro" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuario_id" int,
  "mes" varchar(7),
  "consumo_kwh" decimal,
  "ahorro_clp" decimal,
  "reduccion_huella_co2" decimal,
  "comparacion_mes_anterior" decimal,
  "fecha_calculo" datetime
);

ALTER TABLE "dispositivos" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "registros_consumo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "registros_consumo" ADD FOREIGN KEY ("dispositivo_id") REFERENCES "dispositivos" ("id");

ALTER TABLE "predicciones_consumo" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "notificaciones" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");

ALTER TABLE "metricas_ahorro" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id");
